using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Elephant.Constants.MockData
{
	/// <summary>
	/// City name mock data.
	/// </summary>
	public static class Cities
	{
		/// <summary>
		/// 10 unique largest United States cities, sorted by population from 2013.
		/// </summary>
		public static readonly ReadOnlyCollection<string> Us10 = new(new List<string>
		{
			"New York",
			"Los Angeles",
			"Chicago",
			"Houston",
			"Philadelphia",
			"Phoenix",
			"San Antonio",
			"San Diego",
			"Dallas",
			"San Jose",
		});

		/// <summary>
		/// 100 unique largest United States cities, sorted by population from 2013.
		/// </summary>
		public static readonly ReadOnlyCollection<string> Us100 = new(new List<string>
		{
			"New York",
			"Los Angeles",
			"Chicago",
			"Houston",
			"Philadelphia",
			"Phoenix",
			"San Antonio",
			"San Diego",
			"Dallas",
			"San Jose",
			"Austin",
			"Indianapolis",
			"Jacksonville",
			"San Francisco",
			"Columbus",
			"Charlotte",
			"Fort Worth",
			"Detroit",
			"El Paso",
			"Memphis",
			"Seattle",
			"Denver",
			"Washington",
			"Boston",
			"Nashville-Davidson",
			"Baltimore",
			"Oklahoma City",
			"Louisville/Jefferson County",
			"Portland",
			"Las Vegas",
			"Milwaukee",
			"Albuquerque",
			"Tucson",
			"Fresno",
			"Sacramento",
			"Long Beach",
			"Kansas City",
			"Mesa",
			"Virginia Beach",
			"Atlanta",
			"Colorado Springs",
			"Omaha",
			"Raleigh",
			"Miami",
			"Oakland",
			"Minneapolis",
			"Tulsa",
			"Cleveland",
			"Wichita",
			"Arlington",
			"New Orleans",
			"Bakersfield",
			"Tampa",
			"Honolulu",
			"Aurora",
			"Anaheim",
			"Santa Ana",
			"St. Louis",
			"Riverside",
			"Corpus Christi",
			"Lexington-Fayette",
			"Pittsburgh",
			"Anchorage",
			"Stockton",
			"Cincinnati",
			"St. Paul",
			"Toledo",
			"Greensboro",
			"Newark",
			"Plano",
			"Henderson",
			"Lincoln",
			"Buffalo",
			"Jersey City",
			"Chula Vista",
			"Fort Wayne",
			"Orlando",
			"St. Petersburg",
			"Chandler",
			"Laredo",
			"Norfolk",
			"Durham",
			"Madison",
			"Lubbock",
			"Irvine",
			"Winston-Salem",
			"Glendale",
			"Garland",
			"Hialeah",
			"Reno",
			"Chesapeake",
			"Gilbert",
			"Baton Rouge",
			"Irving",
			"Scottsdale",
			"North Las Vegas",
			"Fremont",
			"Boise City",
			"Richmond",
			"San Bernardino",
		});
	}
}
