# For more info see:
# - https://docs.github.com/en/actions/using-workflows/about-workflows
# - https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build
# - https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack
# - https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-push

############
# Workflow #
############
name: .net CI [Build and Release] # Name of the workflow

############
# Triggers #
############
on:
  push: # Trigger the workflow on a push to the ci branch
    branches:
      - ci
      - master
  pull_request:
    branches:
      - master

##########
#  Jobs  #
##########
jobs:
  checkout-code:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  setup-net-frameworks:
    name: Setup .NET Frameworks
    needs: checkout-code
    runs-on: ubuntu-latest

    # Setup required .NET frameworks.
    steps:
      - name: Setup .NET 2.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.0

      - name: Setup .NET 2.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.1

      - name: Setup .NET 3.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.0

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0

      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup .NET 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

  build-debug:
    name: Build Debug
    needs: setup-net-frameworks
    runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup MAUI Tizen.
      - name: maui-tizen install 1/3
        run: dotnet nuget locals all --clear

      - name: maui-tizen install 2/2
        run: dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

      - name: maui-tizen install 3/3
        run: dotnet workload install android ios maccatalyst macos maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

      # Restore dependencies.
      - name: Restore dependencies
        run: dotnet restore ./Elephant.NuGets.sln

      # Build in Debug configuration
      - name: Build [Debug]
        run: dotnet build ./Elephant.NuGets.sln --configuration Debug --no-restore --nologo --verbosity normal

  build-release:
    name: Build Release
    needs: setup-net-frameworks
    runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup MAUI Tizen.
      - name: maui-tizen install
        run: dotnet nuget locals all --clear

      - name: maui-tizen install
        run: dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

      - name: maui-tizen install
        run: dotnet workload install android ios maccatalyst macos maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

      # Restore dependencies.
      - name: Restore dependencies
        run: dotnet restore ./Elephant.NuGets.sln

      # Build in Release configuration.
      - name: Build [Release]
        run: dotnet build ./Elephant.NuGets.sln --configuration Release --no-restore --nologo --verbosity normal

  # test-release:
    # name: Test Release
    # needs: build-release
    # runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.
    # steps:
      # - name: Checkout code
        # uses: actions/checkout@v3

      # Run tests in Release configuration.
      - name: Test release
        run: dotnet test ./Elephant.NuGets.sln --configuration Release --verbosity normal

  # pack-release:
    # name: Pack Release
    # needs: test-release
    # runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.
    # steps:
      # - name: Checkout code
        # uses: actions/checkout@v3

      # Restore dependencies.
      - name: Restore dependencies
        run: dotnet restore ./Elephant.NuGets.sln

      # pack app
      - name: pack application
        run: dotnet pack ./Elephant.NuGets.sln --no-build --configuration Release --nologo

  # publish-to-nuget-org:
    # name: Publish NuGets
    # needs:  [build-debug, pack-release]
    # runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.
    # steps:
      # - name: Checkout code
        # uses: actions/checkout@v3

      - name: Publish
        #if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_ORG}} -SkipDuplicate