# For more info see: https://docs.github.com/en/actions/using-workflows/about-workflows

############
# Workflow #
############
name: .net CI [Build and Release] # Name of the workflow

############
# Triggers #
############
on:
  push: # Trigger the workflow on a push to the ci branch
    branches:
      - ci
      - master
  pull_request:
    branches:
      - master

##########
#  Jobs  #
##########
jobs:
  checkout-code: # the "Setup-net-frameworks" job step
    name: Checkout
    runs-on: ubuntu-latest

    # List .net frameworks required
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  setup-net-frameworks: # the "Setup-net-frameworks" job step
    name: Setup .NET Frameworks
    needs: checkout-code
    runs-on: ubuntu-latest

    # List .net frameworks required
    steps:
      - name: Setup .NET 2.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.0

      - name: Setup .NET 2.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.1

      - name: Setup .NET 3.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.0

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0

      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup .NET 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

  build-debug:
    name: Build Debug
    needs: setup-net-frameworks
    runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.

    # List of steps to run in build-debug & release
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      
      # maui tizen install steps
      - name: maui-tizen install
        run: dotnet nuget locals all --clear

      - name: maui-tizen install
        run: dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

      - name: maui-tizen install
        run: dotnet workload install android ios maccatalyst macos maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

      # restore dependencies step
      - name: Restore dependencies
        run: dotnet restore ./Elephant.NuGets.sln

      # build with debug
      - name: Build Debug
        run: dotnet build ./Elephant.NuGets.sln --configuration Debug --no-restore --no-logo

  build-release:
    name: Build Release
    needs: setup-net-frameworks
    runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.

    # List of steps to run in build-debug & release
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      
      # maui tizen install steps
      - name: maui-tizen install
        run: dotnet nuget locals all --clear

      - name: maui-tizen install
        run: dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

      - name: maui-tizen install
        run: dotnet workload install android ios maccatalyst macos maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

      # restore dependencies step
      - name: Restore dependencies
        run: dotnet restore ./Elephant.NuGets.sln

      # build release
      - name: Build Release
        run: dotnet build ./Elephant.NuGets.sln --configuration Release --no-logo

      # test release
      #- name: Test release
      #  run: dotnet test --configuration Release --verbosity normal

      # pack app
      #- name: pack application
      #  run: dotnet pack --no-build --configuration Release

  test-release:
    name: Test Release
    needs: build-release
    runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.

    # List of steps to run in build-debug & release
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      # test release
      - name: Test release
        run: dotnet test --configuration Release --verbosity normal

  pack-release:
    name: Pack Release
    needs: test-release
    runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.

    # List of steps to run in build-debug & release
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      # pack app
      - name: pack application
        run: dotnet pack --no-build --configuration Release

  publish-to-nuget-org:
    name: Publish NuGets
    needs:  [build-debug, pack-release]
    runs-on: windows-latest # Note: ubuntu-latest doesn't work because of MAUI.

    # List of steps to run in build-debug & release
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish
        #if: startsWith(github.ref, 'refs/heads/release')
        #run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_ORG}} --skip-duplicate
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_ORG}}